"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  EN: {
    // Shared UI
    "nav.home": "Home",
    "nav.trips": "Trips",
    "btn.explore": "Explore Now",
    // Destinations Page - Tactical Hub
    "dest.hub_title": "Discovery Feed",
    "dest.hub_subtitle": "Intelligence Tuning",
    "dest.showing_results": "Showing results for",
    "dest.all_destinations": "All Coordinates",
    "dest.found_count": "Units Found",
    "dest.no_results": "No coordinates found for",

    // Sidebar Filters (Five-Pillar System)
    "filter.title": "Filter Intelligence",
    "filter.search_placeholder": "Enter coordinates...",
    "filter.budget": "Budget Tier",
    "filter.climate": "Climate Sync",
    "filter.safety": "Safety Tier",
    "filter.duration": "Timeframe",
    "filter.region": "Regional Hub",

    // Sorting
    "sort.popularity": "Popularity",
    "sort.safety": "Safety Index",
    "sort.price": "Budget",
    "sort.temp": "Climate",
    "save_trip_title": "Book Your Trip",

    // Destination Card Tactical Metrics
    "card.safety_label": "Safety",
    "card.duration_label": "Duration",
    "card.budget_label": "Est. Daily",
    "card.best_time": "Optimal Now",
    "card.view_specs": "Analyze Node",
    "card.temp_unit": "°C",
    
    // Banner
    "banner.tag1": "Industrial Planning",
    "banner.title1": "Precision Travel,",
    "banner.high1": "Expertly Crafted",
    "banner.desc1": "The world's first industrial-grade travel planner with real-time global data synchronization.",
    "banner.tag2": "Smart Economy",
    "banner.title2": "Budget Better,",
    "banner.high2": "Explore Further",
    "banner.desc2": "Our automated cost estimator calculates local taxes and transport so you never go over budget.",
    "banner.tag3": "Group Synergy",
    "filter.title": "Tactical Filter",
"filter.sort_label": "Sort Mode",
"sort.default": "Default Analysis",
"sort.price_low": "Budget: Low to High",
"sort.price_high": "Budget: High to Low",
"sort.rating": "Highest Popularity",
"filter.clear": "Clear System",
    "banner.title3": "Collaborative Ready,",
    "banner.high3": "Real-Time Sync",
    "banner.desc3": "Invite your crew to vote on locations and split costs instantly with professional organization.",
    "search.location": "Location",
"search.placeholder": "Where is your next story?",
"search.button": "Plan Adventure",
"search.popular": "Popular:",
"builder.badge": "Industrial UX",
  "builder.title": "THE SMART BUILDER",
  "builder.subtitle": "Drag to reorder. Watch your route optimize in real-time.",
  "builder.day_title": "Day 1: Arrival & Exploration",
  "cat.all": "All",
  "cat.adventure": "Adventure",
  "cat.luxury": "Luxury",
  "cat.budget": "Budget",
  "cat.solo": "Solo",
  "cat.starting": "Starting at",
  // City names as fallback
  "Bali": "Bali",
  "Paris": "Paris",
  "Tokyo": "Tokyo",
  "builder.stops_count": "3 STOPS SCHEDULED",
  "builder.next_dest": "Next Destination",
  // Activity Items
  "activity.sightseeing": "Sightseeing: Old Town",
  "activity.lunch": "Local Gourmet Lunch",
  "activity.walk": "Sunset Coastal Walk",
  "whats_included": "What's Included",
  "tour_plan": "Tour Plan",
  "person": "person",
  "city_tour_title": "City Tour",
  "check_in": "Check In",
  "btn_save_trip": "Save to My Trips",
  "arrival_title": "Arrival & Welcome Dinner",
  "overview": "Overview",
    "whats_included": "What's Included",
    "tour_plan": "Tour Plan",
    "itinerary": "Itinerary",
    "important_info": "Important Information",
    "faq": "FAQ",
    "customer_reviews": "Customer Reviews",
    "related_tours": "Related Tours",
    "price_per_person": "person",
    "daily_budget": "Daily budget",
    "check_in": "Check In",
    "check_out": "Check Out",
    "guests": "Guests",
    "book_now": "Book Now",
    "contact_us": "Contact Us",
    "save_to_trips": "Save to My Trips",
    "login_required": "Please login first to save trips 🙏",
    "save_success": "Trip added to My Trips! ✅",
    "guide": "Professional Tour Guide",
    "hotel": "Luxury Accommodation",
    "meals": "All Meals & Beverages",
    "transfer": "Airport Transfers",
    "tickets": "Entry Tickets & Permits",
    "insurance": "Travel Insurance",
    "day": "Day",
    "nature": "Nature",
    "adventure": "Adventure",
    "visa": "Visa Requirements",
    "safety": "Health & Safety",
    "packing": "What to Pack",
    "cancellation": "Cancellation Policy",

    // Weather Component
    "weather.intel": "Weather Intel",
    "weather.feels": "Feels Like",
    "weather.humidity": "Humidity",
    "weather.wind": "Wind Speed",
    "weather.status": "Sync Status",
    "weather.live": "Live",
    "searchplaceholder": "Search Destination Intel...",
    
    // Trip Room
    "room.title": "TRIP ROOM",
    "room.online": "Online Now",
    "room.sync": "Synchronized",
    "room.enter": "ENTER TRIP ROOM",
    "tour.detail_label": "Detail",
    "tour.what_to_expect": "What to Expect",
    "tour.itinerary": "Itinerary",
    "tour.map": "Map",
    "tour.price_includes": "Price Includes",
    "tour.price_excludes": "Price Excludes",
    "tour.max_people": "Max People",
    "tour.view_map": "View on Map",
    "tour.book_now": "Book This Tour",
    "tour.from_price": "From",
    
    "tour.day": "Day",
    "tour.reviews": "Reviews",
    "tour.confidence_title": "Book With Confidence",
    "tour.confidence_list": "Best price guarantee, 24/7 Support, Hand-picked Hotels",
    "tour.save_wishlist": "Save to Wishlist",
    "tour.share": "Share",
"contact_hero_title": "Connect With Us",
  "contact_hero_subtitle": "We're here to help you navigate your journey.",
  "contact_info_title": "Information",
  "contact_email_label": "Email",
  "contact_phone_label": "Phone",
  "contact_location_label": "Location",
  "contact_location_value": "Dhaka, Bangladesh",
  "contact_form_title": "Send a Message",
  "contact_label_name": "Name",
  "contact_label_email": "Email",
  "about_hero_badge": "Since 2024",
  "about_hero_title": "Connecting the Global Traveler.",
  "about_hero_desc": "Travelee is the digital backbone for modern exploration. We've built an ecosystem that simplifies movement, ensures safety, and democratizes access to the world.",
  "about_quote": "The journey is the product.",
  "about_pillar_1_title": "Precision Driven",
  "about_pillar_1_desc": "Every line of code is written with a purpose: absolute reliability in every timezone.",
  "about_pillar_2_title": "Security First",
  "about_pillar_2_desc": "We protect your data like it's our own, using quantum-ready encryption standards.",
  "about_pillar_3_title": "Limitless Speed",
  "about_pillar_3_desc": "Global edge computing ensures your travel plans update in real-time.",
  "about_journey_title": "Our Journey",
  "about_journey_subtitle": "The milestones that define our rapid evolution.",
  "about_impact_title": "Scaling globally, acting locally.",
  "about_stat_users": "Active Users",
  "about_stat_countries": "Countries",
  "about_stat_api": "API Requests",
  "about_stat_uptime": "Uptime",
  "about_team_title": "The Minds Behind Travelee",
  "about_team_subtitle": "A diverse collective of engineers, explorers, and dreamers.",
  "about_team_btn": "Meet the whole team",
  "about_cta_title": "Ready to explore?",
  "about_cta_desc": "Join the 1.2 million users who are already traveling smarter.",
  "about_cta_btn_start": "Get Started Now",
  "about_cta_btn_sales": "Contact Sales",
  "contact_label_message": "Message",
  "trips_loading_msg": "Loading your adventures...",
  "trips_login_required": "Please login first to see your saved trips 🙏",
  "trips_delete_confirm": "Are you sure you want to delete this trip?",
  "trips_modal_close": "Close",
  "trips_empty_title": "No Trips Found",
  "trips_empty_desc": "Start exploring and save your first journey!",
  "contact_placeholder_message": "Your message...",
  "contact_btn_send": "Send Message",
  "contact_support_live": "Live Support",
  "contact_support_live_desc": "Average response time: 2 minutes",
  "contact_support_partner": "Partnerships",
  "contact_support_partner_desc": "Join our network of 45+ countries.",
  "contact_weekly_intel": "Weekly Intel",
  "contact_newsletter_desc": "Get the latest travel insights and deals.",
    // Cities (Keep keys exactly as they come from API)
    "Phuket": "Phuket",
    "Dhaka": "Dhaka",
    "Tokyo": "Tokyo",
    "clear sky": "Clear Sky",
    "overcast clouds": "Overcast Clouds",
    "broken clouds": "Broken Clouds",
    "scattered clouds": "Scattered Clouds",
    "light rain": "Light Rain",
    "search.label": "Location",
  "search.placeholder": "Where is your next story?",
  "search.button": "Plan Adventure",
  "search.popular": "Popular:",
  "Bali": "Bali",
  "Paris": "Paris",
  "Tokyo": "Tokyo",
  "Swiss Alps": "Swiss Alps",
  "trending.sync": "Synchronizing Data",
  "trending.title": "Global",
  "trending.highlight": "Momentum",
  "trending.metric_label": "Real-time planning metrics from Travelee nodes",
  "trending.active_sessions": "Active Sessions",
  "trending.pop_index": "Popularity Index",
  "trending.view_specs": "VIEW SPECS",
  "trending.avg_budget": "Avg Budget",
  "trending.best_visit": "Best Visit",
  "trending.init_plan": "Initialize Plan",
  // Cities/Countries (if not already there)
  "Phuket": "Phuket",
  "Thailand": "Thailand",
  "Paris": "Paris",
  "budget.fiscal": "Fiscal Analysis",
  "budget.title": "COST",
  "budget.subtitle": "PROJECTION",
  "budget.duration": "Duration of stay",
  "budget.days": "DAYS",
  "budget.total_label": "Estimated Total Expense",
  "budget.allocation": "Resource Allocation",
  "budget.stay": "Stay",
  "budget.food": "Food",
  "budget.transport": "Transport",
  "France": "France",
  "review.badge": "Curated Intelligence",
  "review.title": "TOP",
  "review.subtitle": "USER INTEL",
  "review.displaying": "Displaying Featured",
  "review.archive": "Access Full Archive",
  "review.verified": "Verified User",
  "review.id_prefix": "ID",
  "room.badge_mockup": "Collaborative War-Room",
  "room.expedition": "EXPEDITION",
  "room.status_label": "Status",
  "room.sync": "Synchronized",
  "room.density": "Itinerary Density",
  "room.active_planners": "Current Active",
  "room.planners_count": "6 Planners",
  "room.main_badge": "Multiplayer Planning",
  "room.title_main": "Plan Together,",
  "room.title_sub": "Never",
  "room.title_end": "Solo.",
  "room.description": "Eliminate the endless back-and-forth text threads. Dive into a tactical room where your squad builds the dream trip in real-time.",
  "room.feature_title": "Encrypted Room",
  "room.feature_sub": "Private & Secure Sessions",
  "room.cta": "Create Your Trip Room",
  "footer.news_title": "Join the Elite",
  "footer.news_sub": "Get tactical travel intel and secret deals once a week.",
  "footer.placeholder": "Enter your email...",
  "footer.subscribe": "Subscribe",
  "footer.col1_title": "Company",
  "footer.col2_title": "Destinations",
  "footer.col3_title": "Resources",
  "footer.col4_title": "Socials",
  "footer.rights": "All Rights Reserved.",
  "budget.badge": "Fiscal Analysis",
  "budget.title": "COST",
  "budget.subtitle": "PROJECTION",
  "budget.duration_label": "Duration of stay",
  "budget.days_unit": "DAYS",
  "budget.total_label": "Estimated Total Expense",
  "budget.allocation_title": "Resource Allocation",
  "budget.cat_stay": "Stay",
  "budget.cat_food": "Food",
  "budget.cat_transport": "Transport",
  },
  BN: {
    "nav.home": "হোম",
    "budget.badge": "আর্থিক বিশ্লেষণ",
  "budget.title": "খরচ",
  "budget.subtitle": "প্রাক্কলন",
  "budget.duration_label": "অবস্থানের সময়কাল",
  "budget.days_unit": "দিন",
  "budget.total_label": "আনুমানিক মোট ব্যয়",
  "budget.allocation_title": "সম্পদ বরাদ্দ",
  "budget.cat_stay": "থাকা",
  "budget.cat_food": "খাবার",
  "budget.cat_transport": "পরিবহন",
    "footer.news_title": "এলিট টিমে যোগ দিন",
  "footer.news_sub": "সপ্তাহে একবার ভ্রমণ ইনটেল এবং গোপন ডিল পান।",
  "footer.placeholder": "আপনার ইমেল লিখুন...",
  "footer.subscribe": "সাবস্ক্রাইব",
  "footer.col1_title": "কোম্পানি",
  "footer.col2_title": "গন্তব্য",
  "footer.col3_title": "রিসোর্স",
  "footer.col4_title": "সোশ্যাল",
  "footer.rights": "সর্বস্বত্ব সংরক্ষিত।",
    "review.badge": "সংগৃহীত বুদ্ধিমত্তা",
    "room.badge_mockup": "সহযোগিতামূলক ওয়ার-রুম",
  "room.expedition": "অভিযান",
  "save_trip_title":"এই ট্যুরটি বুক করুন", 
  "room.status_label": "অবস্থা",
  "room.sync": "সুসংগত (লাইভ)",
  "room.density": "ভ্রমণসূচীর ঘনত্ব",
  "room.active_planners": "বর্তমানে সক্রিয়",
  "room.planners_count": "৬ জন প্ল্যানার",
  "room.main_badge": "মাল্টিপ্লেয়ার প্ল্যানিং",
  "room.title_main": "একসাথে পরিকল্পনা করুন,",
  "room.title_sub": "কখনো একা নয়",
  "room.title_end": "।",
  "room.description": "বারবার টেক্সট মেসেজ পাঠানোর ঝামেলা দূর করুন। এমন একটি টেকনিক্যাল রুমে যোগ দিন যেখানে আপনার পুরো দল রিয়েল-টাইমে স্বপ্নের ভ্রমণ তৈরি করবে।",
  "room.feature_title": "এনক্রিপ্ট করা রুম",
  "room.feature_sub": "ব্যক্তিগত ও নিরাপদ সেশন",
  "room.cta": "আপনার ট্রিপ রুম তৈরি করুন",
  "review.title": "সেরা",
  "review.subtitle": "ব্যবহারকারী ইনটেল",
  "review.displaying": "ফিচারড প্রদর্শিত হচ্ছে",
  "review.archive": "সম্পূর্ণ আর্কাইভ দেখুন",
  "review.verified": "যাচাইকৃত ব্যবহারকারী",
  "review.id_prefix": "আইডি",
    "budget.fiscal": "আর্থিক বিশ্লেষণ",
  "budget.title": "খরচ",
  "budget.subtitle": "প্রক্ষেপণ",
  "budget.duration": "থাকার সময়কাল",
  "budget.days": "দিন",
  "budget.total_label": "আনুমানিক মোট ব্যয়",
  "budget.allocation": "সম্পদ বরাদ্দ",
  "budget.stay": "থাকা",
  "budget.food": "খাবার",
  "budget.transport": "যাতায়াত",
    "cat.all": "সব",
  "cat.adventure": "অ্যাডভেঞ্চার",
  "cat.luxury": "বিলাসবহুল",
  "cat.budget": "বাজেট",
  "cat.solo": "একাকী",
  "cat.starting": "শুরু",
  // City names
  "Bali": "বালি",
  "Paris": "প্যারিস",
  "Tokyo": "টোকিও",
    "trending.sync": "ডেটা সিঙ্ক্রোনাইজ করা হচ্ছে",
  "trending.title": "বৈশ্বিক",
  "trending.highlight": "মোমেন্টাম",
  "trending.metric_label": "ট্রাভেলি নোড থেকে রিয়েল-টাইম পরিকল্পনা মেট্রিক্স",
  "trending.active_sessions": "সক্রিয় সেশন",
  "trending.pop_index": "জনপ্রিয়তা সূচক",
  "trending.view_specs": "বিস্তারিত দেখুন",
  "trending.avg_budget": "গড় বাজেট",
  "trending.best_visit": "ভ্রমণের সেরা সময়",
  "trending.init_plan": "পরিকল্পনা শুরু করুন",
  // Cities/Countries
  "Phuket": "ফুকেত",
  "Thailand": "থাইল্যান্ড",
  "Paris": "প্যারিস",
  "France": "ফ্রান্স",
    "nav.trips": "ভ্রমণ",
    "search.label": "অবস্থান",
  "search.placeholder": "আপনার পরবর্তী গন্তব্য কোথায়?",
  "search.button": "ভ্রমণ পরিকল্পনা",
  "search.popular": "জনপ্রিয়:",
  "Bali": "বালি",
  "Paris": "প্যারিস",
  "Tokyo": "টোকিও",
  "Swiss Alps": "সুইস আল্পস",
    "btn.explore": "এখনই এক্সপ্লোর করুন",
    // Destinations Page - Tactical Hub
    "dest.hub_title": "ডিসকভারি ফিড",
    "dest.hub_subtitle": "ইন্টেলিজেন্স টিউনিং",
    "dest.showing_results": "ফলাফল দেখানো হচ্ছে",
    "dest.all_destinations": "সকল গন্তব্য",
    "dest.found_count": "টি ইউনিট পাওয়া গেছে",
    "dest.no_results": "কোনো তথ্য পাওয়া যায়নি",
    "tour.detail_label": "বিস্তারিত",
    "tour.what_to_expect": "ভ্রমণে যা থাকছে",
    "tour.itinerary": "ভ্রমণসূচী",
    "tour.map": "মানচিত্র",
    "tour.price_includes": "প্যাকেজে অন্তর্ভুক্ত",
    "tour.price_excludes": "প্যাকেজের বাইরে",
    "tour.max_people": "সর্বোচ্চ মানুষ",
    "tour.view_map": "ম্যাপে দেখুন",
    "tour.book_now": "বুকিং করুন",
    "tour.from_price": "শুরু",
    "tour.day": "দিন",
    "tour.reviews": "রিভিউ",
    "tour.confidence_title": "নির্ভরতার সাথে বুক করুন",
    "tour.confidence_list": "সেরা দামের নিশ্চয়তা, ২৪/৭ সাপোর্ট, বাছাইকৃত হোটেল",
    "tour.save_wishlist": "উইশলিস্টে রাখুন",
    "tour.share": "শেয়ার করুন",

    // Sidebar Filters (Five-Pillar System)
    "filter.title": "ফিল্টার ইন্টেলিজেন্স",
    "filter.search_placeholder": "গন্তব্য খুঁজুন...",
    "filter.budget": "বাজেট টায়ার",
    "filter.climate": "আবহাওয়া সিঙ্ক",
    "filter.safety": "নিরাপত্তা টায়ার",
    "filter.duration": "সময়কাল",
    "filter.region": "আঞ্চলিক হাব",
    "tour_info": "ট্যুর সম্পর্কিত তথ্য",
  "duration": "সময়কাল",
  "best_time": "সেরা সময়",
  "group_size": "গ্রুপ সাইজ",
  "people": "জন",
  "currency": "কারেন্সি",
  "safety_rating": "নিরাপত্তা রেটিং",
  "languages": "ভাষা",
  "need_help": "সাহায্য প্রয়োজন?",
  "expert_help": "আমাদের ভ্রমণ বিশেষজ্ঞরা আপনাকে সাহায্য করতে প্রস্তুত",
  "call": "কল করুন",
  "about_hero_badge": "২০২৪ থেকে",
  "about_hero_title": "বিশ্বজুড়ে পর্যটকদের সংযোগ স্থাপন করছি।",
  "about_hero_desc": "ট্র্যাভালি হলো আধুনিক অনুসন্ধানের ডিজিটাল মেরুদণ্ড। আমরা এমন একটি ইকোসিস্টেম তৈরি করেছি যা ভ্রমণকে সহজ করে এবং নিরাপত্তা নিশ্চিত করে।",
  "about_quote": "ভ্রমণই আমাদের আসল পণ্য।",
  "about_pillar_1_title": "নির্ভুলতা চালিত",
  "about_pillar_1_desc": "কোডের প্রতিটি লাইন একটি নির্দিষ্ট উদ্দেশ্যে লেখা: প্রতিটি টাইমজোনে নিখুঁত নির্ভরযোগ্যতা।",
  "about_pillar_2_title": "নিরাপত্তা সবার আগে",
  "about_pillar_2_desc": "আমরা আপনার ডেটা আমাদের নিজেদের মতোই রক্ষা করি, কোয়ান্টাম-রেডি এনক্রিপশন ব্যবহার করে।",
  "about_pillar_3_title": "অসীম গতি",
  "about_pillar_3_desc": "গ্লোবাল এজ কম্পিউটিং নিশ্চিত করে যে আপনার পরিকল্পনা রিয়েল-টাইমে আপডেট হয়।",
  "about_journey_title": "আমাদের পথচলা",
  "about_journey_subtitle": "আমাদের দ্রুত বিবর্তনের মাইলফলকসমূহ।",
  "about_impact_title": "বিশ্বব্যাপী প্রসার, স্থানীয়ভাবে সেবা।",
  "about_stat_users": "সক্রিয় ব্যবহারকারী",
  "about_stat_countries": "দেশসমূহ",
  "about_stat_api": "এপিআই রিকোয়েস্ট",
  "about_stat_uptime": "আপটাইম",
  "about_team_title": "ট্র্যাভালির পেছনের কারিগররা",
  "about_team_subtitle": "ইঞ্জিনিয়ার, অভিযাত্রী এবং স্বপ্নদ্রষ্টাদের একটি বৈচিত্র্যময় দল।",
  "about_team_btn": "পুরো দলের সাথে পরিচিত হন",
  "about_cta_title": "আপনি কি প্রস্তুত?",
  "about_cta_desc": "১.২ মিলিয়ন ব্যবহারকারীর সাথে যোগ দিন যারা ইতিমধ্যেই স্মার্টলি ভ্রমণ করছেন।",
  "about_cta_btn_start": "এখনই শুরু করুন",
  "about_cta_btn_sales": "সেলস টিমে যোগাযোগ করুন",

    // Sorting
    "sort.popularity": "জনপ্রিয়তা",
    "trips_loading_msg": "আপনার ভ্রমণ তালিকা লোড হচ্ছে...",
  "trips_login_required": "আপনার সংরক্ষিত ট্রিপগুলো দেখতে আগে লগইন করুন 🙏",
  "trips_delete_confirm": "আপনি কি নিশ্চিত যে এই ট্রিপটি মুছে ফেলতে চান?",
  "trips_modal_close": "বন্ধ করুন",
  "trips_empty_title": "কোনো ট্রিপ পাওয়া যায়নি",
  "trips_empty_desc": "নতুন জায়গা ঘুরে দেখুন এবং আপনার প্রথম যাত্রাটি সেভ করুন!",
    "sort.safety": "নিরাপত্তা সূচক",
    "hero_title": "আমাদের সাথে যোগাযোগ করুন",
    "hero_subtitle": "আপনার ভ্রমণ সহজ করতে আমরা আছি আপনার পাশে।",
    "info_title": "তথ্য",
    "form_title": "বার্তা পাঠান",
    "label_name": "নাম",
    "label_email": "ইমেইল",
    "label_message": "বার্তা",
    "placeholder_message": "আপনার বার্তা এখানে লিখুন...",
    "btn_send": "বার্তা পাঠান",
    "support_live": "লাইভ সাপোর্ট",
    "contact_hero_title": "আমাদের সাথে যোগাযোগ করুন",
  "contact_hero_subtitle": "আপনার ভ্রমণ সহজ করতে আমরা আছি আপনার পাশে।",
  "contact_info_title": "তথ্য",
  "contact_email_label": "ইমেইল",
  "contact_phone_label": "ফোন",
  "contact_location_label": "ঠিকানা",
  "contact_location_value": "ঢাকা, বাংলাদেশ",
  "contact_form_title": "বার্তা পাঠান",
  "contact_label_name": "নাম",
  "contact_label_email": "ইমেইল",
  "contact_label_message": "বার্তা",
  "contact_placeholder_message": "আপনার বার্তা এখানে লিখুন...",
  "contact_btn_send": "বার্তা পাঠান",
  "contact_support_live": "লাইভ সাপোর্ট",
  "contact_support_live_desc": "গড় উত্তর দেওয়ার সময়: ২ মিনিট",
  "contact_support_partner": "পার্টনারশিপ",
  "contact_support_partner_desc": "৪৫টিরও বেশি দেশে আমাদের নেটওয়ার্কে যোগ দিন।",
  "contact_weekly_intel": "উইকলি ইনটেল",
  "contact_newsletter_desc": "সর্বশেষ ভ্রমণ তথ্য এবং অফারগুলো সরাসরি পান।",
    "support_live_desc": "গড় উত্তর দেওয়ার সময়: ২ মিনিট",
    "support_partner": "পার্টনারশিপ",
    "support_partner_desc": "৪৫টিরও বেশি দেশে আমাদের নেটওয়ার্কে যোগ দিন।",
    "sort.price": "বাজেট",
    "sort.temp": "জলবায়ু",

    // Destination Card Tactical Metrics
    "card.safety_label": "নিরাপত্তা",
    "card.duration_label": "সময়কাল",
    "card.budget_label": "দৈনিক খরচ",
    "card.best_time": "ভ্রমণের সঠিক সময়",
    "card.view_specs": "বিস্তারিত বিশ্লেষণ",
    "card.temp_unit": "°সে.",
    "home": "হোম",
    "city_tour_title": "শহর ঘুরে দেখা",
    "destinations": "গন্তব্যস্থল",
    "overview": "একনজরে",
    "whats_included": "যা যা থাকছে",
    "tour_plan": "ভ্রমণ পরিকল্পনা",
    "itinerary": "ভ্রমণসূচী",
    "important_info": "গুরুত্বপূর্ণ তথ্য",
    "faq": "সাধারণ জিজ্ঞাসা",
    "customer_reviews": "গ্রাহকদের রিভিউ",
    "related_tours": "সম্পর্কিত ট্যুর",
    "price_per_person": "জনপ্রতি",
    "daily_budget": "দৈনিক বাজেট",
    "check_in": "চেক-ইন",
    "check_out": "চেক-আউট",
    "guests": "অতিথি সংখ্যা",
    "book_now": "বুক করুন",
    "contact_us": "যোগাযোগ করুন",
    "save_to_trips": "ভ্রমণ তালিকায় সেভ করুন",
    "login_required": "ভ্রমণ সেভ করতে আগে লগইন করুন 🙏",
    "save_success": "ভ্রমণ তালিকায় যুক্ত হয়েছে! ✅",
    "duration": "ভ্রমণের সময়কাল",
    "day": "দিন",
    "guide": "প্রফেশনাল ট্যুর গাইড",
    "hotel": "বিলাসবহুল আবাসন",
    "meals": "সকল খাবার ও পানীয়",
    "transfer": "এয়ারপোর্ট ট্রান্সফার",
    "tickets": "প্রবেশ টিকিট ও পারমিট",
    "insurance": "ভ্রমণ বীমা",
    "wifi": "ফ্রি ওয়াইফাই",
    "nature": "প্রকৃতি",
    "whats_included": "যা যা অন্তর্ভুক্ত",
  "tour_plan": "ট্যুর প্ল্যান",
  "person": "জনপ্রতি",
  "check_in": "চেক ইন",
  "btn_save_trip": "ভ্রমণ তালিকায় সেভ করুন",
  "arrival_title": "আগমন ও স্বাগত ডিনার",
    "adventure": "অ্যাডভেঞ্চার",
    "visa": "ভিসা সংক্রান্ত তথ্য",
    "safety": "স্বাস্থ্য ও নিরাপত্তা",
    "packing": "সাথে যা যা নেবেন",
    "cancellation": "বাতিল করার নিয়ম",

    "banner.tag1": "ইন্ডাস্ট্রিয়াল প্ল্যানিং",
    "banner.title1": "নিখুঁত ভ্রমণ,",
    "banner.high1": "দক্ষতার সাথে নির্মিত",
    "banner.desc1": "রিয়েল-টাইম গ্লোবাল ডেটা সিনক্রোনাইজেশন সহ বিশ্বের প্রথম ইন্ডাস্ট্রিয়াল-গ্রেড ট্রাভেল প্ল্যানার।",
    "banner.tag2": "স্মার্ট ইকোনমি",
    "banner.title2": "বাজেট প্ল্যানিং,",
    "banner.high2": "বেশি এক্সপ্লোরেশন",
    "banner.desc2": "আমাদের অটোমেটেড কস্ট এস্টিমেটর ট্যাক্স এবং ট্রান্সপোর্ট খরচ হিসাব করে, যাতে বাজেট না ছাড়ায়।",
    "banner.tag3": "গ্রুপ সিনার্জি",
    "banner.title3": "কোলাবোরেটিভ রেডি,",
    "builder.badge": "ইন্ডাস্ট্রিয়াল UX",
  "builder.title": "স্মার্ট বিল্ডার",
  "builder.subtitle": "রিঅর্ডার করতে ড্র্যাগ করুন। রিয়েল-টাইমে আপনার রুট অপ্টিমাইজড দেখুন।",
  "builder.day_title": "দিন ১: আগমন ও অন্বেষণ",
  "builder.stops_count": "৩টি স্টপ নির্ধারিত",
  "builder.next_dest": "পরবর্তী গন্তব্য",
  // Activity Items
  "activity.sightseeing": "দর্শনীয় স্থান: ওল্ড টাউন",
  "activity.lunch": "স্থানীয় দুপুরের খাবার",
  "activity.walk": "সূর্যাস্তকালীন উপকূলীয় হাঁটা",
    "banner.high3": "রিয়েল-টাইম সিঙ্ক",
    "banner.desc3": "বন্ধুদের ইনভাইট করুন ভোট দিতে এবং খরচ ভাগ করে নিতে রিয়েল-টাইমে।",
    "search.location": "অবস্থান",
"search.placeholder": "আপনার পরবর্তী গন্তব্য কোথায়?",
"search.button": "ভ্রমণ পরিকল্পনা",
"search.popular": "জনপ্রিয়:",
"filter.title": "ফিল্টার কন্ট্রোল",
"filter.sort_label": "সর্টিং মোড",
"sort.default": "ডিফল্ট এনালাইসিস",
"sort.price_low": "বাজেট: কম থেকে বেশি",
"sort.price_high": "বাজেট: বেশি থেকে কম",
"sort.rating": "সর্বোচ্চ জনপ্রিয়তা",
"filter.clear": "সিস্টেম ক্লিয়ার করুন",

    "weather.intel": "আবহাওয়া তথ্য",
    "weather.feels": "অনুভূত তাপমাত্রা",
    "weather.humidity": "আর্দ্রতা",
    "weather.wind": "বাতাসের গতি",
    "weather.status": "সিঙ্ক স্ট্যাটাস",
    "weather.live": "লাইভ",
    "searchplaceholder": "গন্তব্য তথ্য খুঁজুন...",

    "room.title": "ট্রিপ রুম",
    "room.online": "সক্রিয় আছেন",
    "room.sync": "সংযুক্ত",
    "room.enter": "রুমে প্রবেশ করুন",

    "Phuket": "ফুকেত",
    "Dhaka": "ঢাকা",
    "Tokyo": "টোকিও",
    "clear sky": "পরিষ্কার আকাশ",
    "overcast clouds": "মেঘাচ্ছন্ন আকাশ",
    "broken clouds": "আংশিক মেঘলা",
    "scattered clouds": "বিচ্ছিন্ন মেঘ",
    "light rain": "হালকা বৃষ্টি"
  }
};

const cityMap = {
  "ঢাকা": "Dhaka",
  "ফুকেত": "Phuket",
  "সিলেট": "Sylhet",
  "চট্টগ্রাম": "Chittagong",
  "কক্সবাজার": "Cox's Bazar",
  "রংপুর": "Rangpur",
  "খুলনা": "Khulna",
  "বরিশাল": "Barisal",
  "কুমিল্লা": "Comilla",
  "গাজীপুর": "Gazipur"
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');

  useEffect(() => {
    const savedLang = localStorage.getItem('travelee_lang');
    if (savedLang) setLang(savedLang);
  }, []);

  const toggleLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('travelee_lang', newLang);
  };

  const t = (key) => {
    if (!key) return "";
    // REMOVED .toLowerCase() to ensure exact key matching (banner.tag1 != BANNER.TAG1)
    const lookupKey = key.trim();
    return translations[lang][lookupKey] || key;
  };

  const convertToEnglish = (input) => {
    if (!input) return "";
    const trimmed = input.trim();
    return cityMap[trimmed] || trimmed;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t, convertToEnglish }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};